language: julia
os:
  - linux
  # - osx
# arch: arm64-graviton2

julia:
  - 1.2
  - 1.4
  - nightly

notifications:
  email: false

after_success:
  # - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  allow_failures:
  - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        # - julia --project=perf/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
        #                                        Pkg.instantiate()'
        # - julia --project=perf/ perf/samplers.jl
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip